export const NAMIBIAN_TOWNS = [
  "Windhoek",
  "Swakopmund",
  "Walvis Bay",
  "Okahandja",
  "Otjiwarongo",
  "Gobabis",
  "Tsumeb",
  "Grootfontein",
  "Mariental",
  "Keetmanshoop",
  "Oshakati",
  "Rundu",
  "Katima Mulilo",
  "Lüderitz",
  "Henties Bay",
  "Usakos",
  "Karasburg",
  "Outjo",
  "Omaruru",
  "Sesriem",
  "Oshivelo",
  "Omuthiya",
  "Ondangwa",
  "Okakarara",
  "Arandis",
  "Witvlei",
  "Omaruru",
  "Kalkfeld",
  "Khorixas",
  "Kamanjab",
  "Gibeon",
  "Maltahohe",
  "Karibib",
  "Groot Aub",
  "Rehoboth",
  "Otavi",
  "Kombat",
  "Omitara",
  "Berseba",
  "Tses",
];