export const NAMIBIAN_TOWNS = [
  "Windhoek",
  "Swakopmund",
  "Walvis Bay",
  "Okahandja",
  "Otjiwarongo",
  "Gobabis",
  "Tsumeb",
  "Grootfontein",
  "Mariental",
  "Keetmanshoop",
  "Oshakati",
  "Rundu",
  "Katima Mulilo",
  "Lüderitz",
  "Henties Bay",
  "Usakos",
  "Karasburg",
  "Outjo",
  "Omaruru",
  "Sesriem",
];