name: Build and deploy Node.js app to Azure Web App - Treba

on:
  push:
    branches:
      - treba-azure-migration
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3BB1AB4369A84E0498BB4D25385A3610 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3C148A325CEB4E719D963471F2A2F79E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DB360982AFC64FFDA196BE277567D376 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Treba
          slot-name: Production
          package: .
